name: "Gin Jwt Authentication"

services:
  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - GinJwtNetwork

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT} 
    networks:
      - GinJwtNetwork

networks:
  GinJwtNetwork: